### ISSUE TITLE
plugin.xml not found

### ISSUE THREAD

**Issue by makinux-git** [varunkumar/phonegap-missedcall-plugin#1]
I can't build this plugin because there is no plugin.xml file found

I am using cordova and netbeans to build android sample of this plugin.

I tried to create a new plugin.xml file and I am getting a lot of issues.

**Comment by lfrodrigues** [comment]
This has been fixed in #3 @varunkumar I think you can close this

**Comment by varunkumar** [comment]
Thanks @lfrodrigues for the fix
